platform :ios, '15.5'
inhibit_all_warnings!

target 'Photos' do
  use_frameworks!

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  target 'PhotosTests' do
    inherit! :search_paths
    pod 'RxTest'
    pod 'RxBlocking'
  end
end
